package constants

const (
	COLON                           = ":"
	PIPE_WITH_SPACES                = " | "
	HYPHEN_WITH_SPACES              = " - "
	EMPTY_TEXT                      = ""
	SPACE                           = " "
	NUMBER_ONE_INT                  = 1
	VERSAO                          = "Versão:"
	SEGUNDO                         = "segundo"
	SEGUNDOS                        = "segundos"
	VEZ                             = "vez"
	VEZES                           = "vezes"
	BEM_VINDO                       = "Bem-vindo ao sistema de monitoramento!"
	MENU_PRINCIPAL                  = "Menu principal:"
	DIGITE_OPCAO                    = "Digite o número da opção desejada:"
	RETORNAR_MENU_ANTERIOR          = "Retornar ao menu anterior."
	CANCELAR_RETORNAR_MENU_ANTERIOR = "Operação cancelada! Retornando ao menu anterior."
	OPCAO_ESCOLHIDA                 = "Opção escolhida: "
	OPCAO_INVALIDA_DIGITE           = "Opção inválida!\n" +
		"Digite um número dentre as opções exibidas no menu!"
	OPCAO_INVALIDA_RETORNA              = "Opção inválida! Retornando ao menu anterior!"
	INICIAR_MONITORAMENTO               = "1 - Iniciar monitoramento"
	EXIBIR_LOGS                         = "2 - Exibir logs"
	LIMPAR_LOGS                         = "3 - Limpar logs"
	EXIBIR_LISTA_SITES                  = "4 - Exibir lista de sites cadastrados"
	CADASTRAR_SITE                      = "5 - Cadastrar site"
	REMOVER_SITE                        = "6 - Remover site"
	CONFIGURACOES_MONITORAMENTO         = "7 - Configuração do monitoramento"
	SAIR_PROGRAMA                       = "8 - Sair do programa"
	MONITORAMENTO_INICIADO              = "Monitoramento iniciado!"
	MONITORAMENTO_FINALIZADO            = "Monitoramento finalizado!"
	TAMANHO_LISTA_SITES                 = "Tamanho da lista de sites: "
	TAMANHO_LISTA_RESPONSES             = "Tamanho da lista de responses:"
	SITE                                = "Site: "
	STATUS                              = "Status: "
	ONLINE                              = "Online"
	OFFLINE                             = "Offline"
	DATA                                = "Data: "
	HORA                                = "Hora: "
	HTTP_STATUS                         = "Status HTTP:"
	SITE_SUCESSO                        = "Situação: Carregado com sucesso!"
	SITE_FALHA                          = "Situação: Erro durante o carregamento!"
	STATUS_DESCONHECIDO                 = "Desconhecido"
	LOGS_CARREGADOS                     = "Lista de logs carregada, iniciando exibição!"
	ELIMINANDO_LOGS                     = "Logs apagados com sucesso!"
	SAINDO_PROGRAMA                     = "Saindo do programa."
	DESPEDIDA                           = "Obrigado por usar o nosso sistema!"
	CADASTRAR_OUTRO_SITE                = "1 - Cadastrar outro site"
	DIGITE_SITE                         = "Digite o endereço do site que deseja cadastrar:"
	EXEMPLO_SITE                        = "Ex.: http://www.google.com"
	SITE_DIGITADO_CADASTRO              = "O endereço digitado foi:"
	INDICE_DIGITADO_REMOCAO             = "O endereço escolhido para remoção foi:"
	REALIZA_CADASTRO_SITE               = "1 - Confirmar endereco do site"
	CANCELAR_CADASTRO_SITE              = "2 - Cancelar cadastro do site"
	DIGITE_INDICE_REMOCAO               = "Digite o número referente ao site que deseja remover:"
	REALIZA_REMOCAO_SITE                = "1 - Confirmar remoção do site"
	CANCELAR_REMOCAO_SITE               = "2 - Cancelar remoção do site"
	SITE_CADASTRADO_SUCESSO             = "Site cadastrado com sucesso!"
	SITE_REMOVIDO_SUCESSO               = "Site removido com sucesso!"
	LISTA_SITES_CADASTRADOS             = "Lista dos sites cadastrados:"
	DELAY_MONITORAMENTO                 = "Tempo entre monitoramentos em segundos (Padrão: 5):"
	QUANTIDADE_REPETICOES_MONITORAMENTO = "Quantas vezes o monitoramento repete automaticamente (Padrão: 1):"
	ALTERAR_DELAY                       = "1 - Alterar o tempo entre monitoramentos"
	ALTERAR_REPETICOES                  = "2 - Alterar quantidade de repetições do monitoramentos"
	RETORNAR_CONFIGURACOES              = "3 - Retornar para o menu de configurações"
	DIGITE_VALOR_DELAY                  = "Digite o intervalo de tempo (em segundos) entre monitoramentos:"
	DIGITE_QUANTIDADE_REPETICOES        = "Digite o a quantidade de repetições automáticas para o monitoramento:"
	ALTERACAO_DELAY_SUCESSO             = "Intervalo de tempo entre monitoramentos alterado com sucesso!"
	ALTERACAO_QUANTIDADE_SUCESSO        = "Quantidade de repetições automáticas para o monitoramento alterada com sucesso!"
	NOVO_VALOR_CONFIGURACAO             = "Novo valor:"
	CONFIRMA_ALTERACAO_CONFIGURACAO     = "1 - Confirmar alteração"
	CANCELA_ALTERACAO_CONFIGURACAO      = "2 - Cancelar alteração"
	VALOR_MINIMO_DELAY                  = "O valor mínimo para o delay é 5!\n" +
		"Retornando ao menu anterior!"
	VALOR_MINIMO_QUANTIDADE = "O valor mínimo para quantidade é 1!\n" +
		"Retornando ao menu anterior!"
	VALOR_REPETIDO_DELAY = "O valor digitado já é o valor atual do delay!\n" +
		"Retornando ao menu anterior!"
	VALOR_REPETIDO_QUANTIDADE = "O valor digitado já é o valor atual da quantidade de repetições!\n" +
		"Retornando ao menu anterior!"
)
